package com.stadtverwaltung.pjms.controller;

import java.util.HashMap;

/**
 * Handles authorization for employee login
 */
public class AuthorizationController {

    /**
     * Saves active sessions in map at runtime
     */
    private static final HashMap<String,String> sessionMap = new HashMap<>();

    /**
     * Checks if parameters are in map to authenticate user
     * @param employeeID employeeID primary key
     * @param sessionID  sessionID in map
     * @return True if request employeeID and sessionID is in map
     */
    public boolean hasAuthorization(String employeeID, String sessionID) {
            if (sessionMap.get(employeeID) != null && sessionID != null) {
                return sessionMap.get(employeeID).equals(sessionID);
            } else {
                return false;
            }
    }

    /**
     * Adds user to map to authenticate
     * @param employeeID employeeID primary key
     * @param sessionID sessionID generated by EmployeeController
     */
    public void addSession(String employeeID, String sessionID) {
        sessionMap.put(employeeID,sessionID);
    }
}
