apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app.kubernetes.io/name: MyApp
  spec:
      containers:
      - name: backend
        image: nginx:1.14.2
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            memory: "128Mi"
            cpu: "500m"
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
