package com.stadtverwaltung.pjms.model;

/**
 * Represents a citizen who publishes a report
 */
public class Citizen {
    /**
     * Unique ID of citizen, generated by Persistence
     */
    public String citizenID;
    /**
     * First name of Citizen
     */
    public String citizenFirstName;
    /**
     * Last name of citizen
     */
    public String citizenLastName;
    /**
     * Phone number of citizen
     */
    public String citizenPhoneNumber;
    /**
     * Email Address of citizen
     */
    public String citizenEmailAddress;

    /**
     * Default constructor
     */
    public Citizen() {}

}
