package com.stadtverwaltung.pjms.persistence;

import com.stadtverwaltung.pjms.model.LoginData;
import org.apache.commons.lang3.RandomStringUtils;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 * Handles Employees on a database level
 */
public class EmployeePersistence {
    /**
     * Instance of SQLite database
     */
    private final SQLiteDatabase sqLiteDatabase = new SQLiteDatabase();
    /**
     * Password class instance for cryptographic tasks
     */
    private final SHA512PasswordPersistence sha512PasswordPersistence = new SHA512PasswordPersistence();

    /**
     * Checks login submitted by data on a database level
     * @param loginData loginData provided by citizen
     * @return SessionID generated by Backend
     * @throws SQLException SQL Exception if anything on databse level goes wrong
     */
    public String checkLogin(LoginData loginData) throws SQLException {
        String securePassword = null;
        String salt = null;

        PreparedStatement preparedStatement = sqLiteDatabase.getConnection().prepareStatement("SELECT employeePassword, employeeSalt FROM employees WHERE employeeID = ?");
        preparedStatement.setString(1,loginData.employeeID);

        ResultSet resultSet = preparedStatement.executeQuery();

        while(resultSet.next()) {
            securePassword = resultSet.getString("employeePassword");
            salt = resultSet.getString("employeeSalt");
        }

        if(sha512PasswordPersistence.verifyUserPassword(loginData.password,securePassword,salt)) {
            return generateSessionID();
        } else {
            return null;
        }

    }

    /**
     * Generates unique sessionID for employee login
     * @return Generated sessionID
     */
    private String generateSessionID() {
        String id;
        id = RandomStringUtils.randomAlphanumeric(32);
        return id;
    }


}
